// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-PXd6aNI9GAxbxcrf73B8JDYH3QuMp1M',
    appId: '1:983165916935:android:2d0bf6773ea03e90d117a2',
    messagingSenderId: '983165916935',
    projectId: 'foursquare-ebook-store',
    storageBucket: 'foursquare-ebook-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI1BxCcoVtTXv4z5eQ0aWr3bm-iSVNbuc',
    appId: '1:983165916935:ios:9d9dfdad28fe1d78d117a2',
    messagingSenderId: '983165916935',
    projectId: 'foursquare-ebook-store',
    storageBucket: 'foursquare-ebook-store.firebasestorage.app',
    androidClientId: '983165916935-7hnq6fs88dcts8lu9u71njrimj4dhjul.apps.googleusercontent.com',
    iosClientId: '983165916935-boerb57flo7l98hkvu48jfb8rshpiebo.apps.googleusercontent.com',
    iosBundleId: 'com.foursquareng.ebook',
  );
}
